# Data manupilation in Numpy

In [ ]:
import numpy as np

data = np.array([[10, 20, 30], [40, 50, 60]])

scaled_data = data * 2
average = np.mean(data)

print(f"Scaled Array:\n{scaled_data}")
print(f"Average Value: {average}")

Scaled Array:
[[ 20  40  60]
 [ 80 100 120]]
Average Value: 35.0


# Slicing and Reshaping Data

In [ ]:
arr = np.arange(12)

# Reshape to a 3x4 matrix
matrix = arr.reshape(3, 4)

subset = matrix[:2, 2:]

print(f"3x4 Matrix:\n{matrix}")
print(f"Subset:\n{subset}")

3x4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Subset:
[[2 3]
 [6 7]]


# Loading and inspecting datasets

In [4]:
import pandas as pd

# Loading a sample dataset (Iris flowers is a classic)
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

# Inspect the first 5 rows and get metadata
df.head() # Shows data types and missing values

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [9]:
df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


# Filter and Query Data

In [13]:
# Find all flowers where sepal_length is greater than 5.0
# and only show the 'species' and 'sepal_length' columns
large_flowers = df[df['sepal_length'] > 5.0][['species', 'sepal_length']]

print(f"Number of large flowers: {len(large_flowers)}")

Number of large flowers: 118


In [12]:
large_flowers.head()

,species,sepal_length
0,setosa,5.1
5,setosa,5.4
10,setosa,5.4
14,setosa,5.8
15,setosa,5.7


# Aggregate and Group Statistics

In [14]:
# Task: Find the average measurements for each species of flower
species_stats = df.groupby('species').mean()

print("Average stats per species:")
print(species_stats)

Average stats per species:
            sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026
